baseURL: "/landingpage-executive"
languageCode: "en-us"
title: "Why FAIR cookbook?"
theme: "hugo-lime"

components: 
  "pricing": true
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

staticDir:
- static
- themes/static